# Generated by Django 4.0.2 on 2022-03-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='validity',
            field=models.DateTimeField(null=True),
        ),
    ]
