# Generated by Django 4.0.2 on 2022-03-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_order_orderedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('body', models.TextField(max_length=1000)),
                ('seen', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_set', to='backend.user')),
            ],
        ),
    ]
