# Generated by Django 4.0.2 on 2022-03-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='fcmtoken',
            field=models.CharField(default=1334, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='validity',
            field=models.DateTimeField(default='2022-02-23 11:11'),
            preserve_default=False,
        ),
    ]
